name: Dispatch event

on:
  repository_dispatch:
    types: [test_result]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Output of the event payload
        env:
          REPO: ${{ github.event.client_payload.repo }}
          VERSION: ${{ github.event.client_payload.version }}
        run: echo $REPO - $VERSION
